# Generated by Django 3.0.8 on 2020-11-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201124_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='user_id',
        ),
    ]
