# Generated by Django 3.0.8 on 2020-11-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201124_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
