# Generated by Django 3.0.8 on 2020-12-01 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201124_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='auction_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='auction_bid', to='auctions.Listings'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
