# Generated by Django 3.0.8 on 2020-12-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listings_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='closed',
        ),
    ]
