# Generated by Django 3.0.8 on 2020-12-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20201222_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='product',
            new_name='auction',
        ),
    ]
