# Generated by Django 3.0.8 on 2020-12-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201222_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.CharField(max_length=64),
        ),
    ]
