# Generated by Django 3.0.8 on 2020-12-23 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20201223_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='auction',
        ),
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Item', to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
